### ISSUE TITLE
汉化过程

### ISSUE THREAD

**Issue by huaiyi255** [raccoon666666/DockerDesktopChinese#1]
汉化是将那些文件直接全部替换掉原先app.asar解压的文件吗

**Comment by huaiyi255** [comment]
> 汉化是将那些文件直接全部替换掉原先app.asar解压的文件吗

可不可以直接将下载的包中app压缩了替换掉原先的文件

**Comment by raccoon666666** [comment]
> > 汉化是将那些文件直接全部替换掉原先app.asar解压的文件吗
> 
> 可不可以直接将下载的包中app压缩了替换掉原先的文件

对, 就是用asar打包后粘贴就行, 当然你提前把初始的app.asar保存了啊, 万一有问题还能转回来

**Comment by huaiyi255** [comment]
> > > 汉化是将那些文件直接全部替换掉原先app.asar解压的文件吗
> > 
> > 
> > 可不可以直接将下载的包中app压缩了替换掉原先的文件
> 
> 对, 就是用asar打包后粘贴就行, 当然你提前把初始的app.asar保存了啊, 万一有问题还能转回来

好嘞，我试试hh
