### ISSUE TITLE
新版本的汉化

### ISSUE THREAD

**Issue by lianxia2020** [raccoon666666/DockerDesktopChinese#3]
目前仓库的app.asar 在新版本使用不了。会白屏卡死等，在README中有提到后续会不断修补，不知道作者有没有考虑新版本的汉化呢，我可以分担一点工作量

**Comment by raccoon666666** [comment]
啊完全没有动力搞了.....但是如果你急用的话可以参照一下我[这里](https://github.com/raccoon666666/StarUML-chinese)提到的汉化方法自己改, 难度没有主要是麻烦( 另外app.asar解压成app文件夹后无需重新压缩也应该能正常打开软件 (至少Postman可以

**Comment by lianxia2020** [comment]
不急，我也会高一点，但是。就翻译的话，我觉得这种不太熟练的话工作量太大。有点麻烦，所以看你有没有兴趣搞的话可以一起搞一下。如果没兴趣的话就这么用也行。毕竟工作量确实有点大。

**Comment by raccoon666666** [comment]
暂时没有汉化新版本的想法..等哪天我自己要用Docker了再说吧
