### ISSUE TITLE
关于docker desktop最新汉化

### ISSUE THREAD

**Issue by hongmengshikong** [raccoon666666/DockerDesktopChinese#4]
由于docker desktop最新版本与现有版本相差太大，实在是无法兼容，有没有兴趣让我帮忙维护。不过遗憾的是我目前不知道这玩意如何汉化，如果可以的话，请告知我汉化流程，我们一起进行汉化

**Comment by waxingren** [comment]
> 由于docker desktop最新版本与现有版本相差太大，实在是无法兼容，有没有兴趣让我帮忙维护。不过遗憾的是我目前不知道这玩意如何汉化，如果可以的话，请告知我汉化流程，我们一起进行汉化

贴主放弃了。。
